### PR TITLE
fix #7520 feat(nimbus): Cancel the review if need to make any changes

### LINKED ISSUE #7520: Add a cancel review button
When a user requests to launch, end enrollment, or end an experiment, the experiment goes into a review state, and there's no way for the owner to cancel that review if they want to go back to make some additional changes.  We should add a 'cancel review request' button that sends it back to idle.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2609)

### PR DESCRIPTION
**Pull request by yashika-khurana**
Because

* When a user requests to `launch`, `end enrollment`, or`end an experiment`, the experiment goes into a `review state`, and there's no way for the owner to `cancel that review` if they want to go back to make some additional changes. 

This commit

* Adds a button to the summary page to 'cancel review request'  and sends the experiment back to `idle state`
* Test cases to verify new changes

Screenshot for the changes
When the user requested to end the experiment/ end enrollment
Screen Shot 2022-08-02 at 2 52 51 PM
Screen Shot 2022-08-02 at 2 52 59 PM
Screen Shot 2022-08-02 at 2 53 04 PM

When the user requested to launch the experiment
Screen Shot 2022-08-02 at 2 49 58 PM
Screen Shot 2022-08-02 at 2 50 06 PM

fixes #7520

### CODE REVIEW

**Review by jaredlockhart — DISMISSED** [review]
Ah, I managed to get it into a wonky state.

1) Create experiment
2) Launch to live and approve in remote settings
3) Request end enrollment
4) Cancel review request
5) Now back to the idle state with a rejected message, but the 'end enrollment' button is gone when it's still in the enrolling state

Screen Shot 2022-08-08 at 3 14 32 PM

**Comment by yashika-khurana** [comment]
@jaredlockhart thank you :) nice catch let me figure it out 🤔

**Comment by yashika-khurana** [comment]
@jaredlockhart buttons are back now 👯 
image

**Review by jaredlockhart — APPROVED** [review]
Yes yes yes!  Just tried all the workflows, they all work perfectly.  The new react component is very simple and clear, the tests are very clear and comprehensive and readable.  Everything looks great thank you @yashika-khurana !

**Pull request merged**
