### PR TITLE
Update custom targeting for Mozilla Rally users

### PR DESCRIPTION
**Pull request by aaga**
We want to change how the custom targeting works for Mozilla Rally users, and also add a new category of targeting for users with our new extension

### CODE REVIEW

**Review by eliserichards — COMMENTED** [review]
This looks good so far! Looks like `make check` is complaining, so you'll need to fix those issues before we get this merged 👍 

Just to confirm, there will be no use for `RALLY_CORE_ADDON_USER` targeting in the future? We can always keep that config if it might be useful

**Comment by jrbenny35** [comment]
image
Thats 🔥

**Comment by aaga** [comment]
@eliserichards Thanks for your comments! I added back `RALLY_CORE_ADDON_USER` just to be safe like you suggested, and after some tinkering was able to re-frame the targeting string so that `make check` is happy

**Review by jaredlockhart — APPROVED** [review]
Awesome looks good to me 👍

**Pull request merged**
