### PR TITLE
fixes #7406 feat(nimbus): add custom targeting for Mozilla Rally users

### LINKED ISSUE #7406: add custom Nimbus targeting for Mozilla Rally Core Add-on users
The Mozilla Rally team wants to run messaging experiments on its users. Since Rally users are a small subset of the population (~12,500) it makes sense to have this be a custom targeting option.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2513)

### PR DESCRIPTION
**Pull request by aaga**
Because the Mozilla Rally team wants to run experiments on only existing users, this commit adds custom targeting that allows us to run experiments on only users who have installed the official Rally Core Add-on

### CODE REVIEW

**Comment by aaga** [comment]
@punamdahiya

**Comment by aaga** [comment]
@punamdahiya

**Review by jaredlockhart — APPROVED** [review]
Yes looks good, thank you @aaga ! 🎉

**Comment by jaredlockhart** [comment]
@aaga Ping me here or on slack when you'd like it merged 👍

**Review by punamdahiya — APPROVED** [review]
LGTM! Thanks for the patch

**Pull request merged**
