### PR TITLE
Fix issue with double quotes in models.py id7900

### PR DESCRIPTION
**Pull request by fadebowaley**
Because
In this commit, I modified the code in the "models.py" file to replace double quotes with single quotes. This was done to improve the code consistency and readability in line with the project coding conventions.
- Reason
Tto improve the code consistency and readability in line with the project coding conventions.
- Change
The main change made in this commit was to replace all instances of double quotes with single quotes in the "models.py" file. This change will help to improve the readability of the code and make it consistent with the project coding standards.

### CODE REVIEW

**Review by yashikakhurana — APPROVED** [review]
thank you @fadebowaley for contributing 👏

**Review by yashikakhurana — CHANGES_REQUESTED** [review]
@fadebowaley one check failed, can you take a look and fixed that, thanks

**Comment by fadebowaley** [comment]
Ok I will check and fix

**Comment by yashikakhurana** [comment]
@fadebowaley closing this PR since it is doing nothing, please feel free to work and submit PR once you are finish with it,t hanks

**Pull request closed without merging**
