### PR TITLE
fixes #8078  bug(nimbus): fix Takeaways edit button vertical padding

### LINKED ISSUE #8078: Takeaways "Edit" button vertical padding
1. Have a "Complete" experiment
2. On the Summary page, click on the "Archive" button on the lefthand side

When you archive the experiment, you can see the "Edit" button on the Takeaways section goes away. When it does, the vertical padding of the Takeaways section changes. This should be a consistent size whether or not the Edit button is present.

https://user-images.githubusercontent.com/43795363/208506481-b19ee2f7-b1e1-45ec-b056-76abcb0aa5aa.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3012)

### PR DESCRIPTION
**Pull request by emmaz12**
Because

- The component containing the edit button's size is changed when the archive button is clicked

This commit

- Allows the component to stay the same size when the archive button is clicked without changing
- Increases the margin for the column containing the Takeaway title and Edit button in order to solve the bug

https://user-images.githubusercontent.com/117552772/223843935-dd12a974-4517-47b3-a143-a22e1423cc89.mov

### CODE REVIEW

**Comment by yashikakhurana** [comment]
@emmaz12 this looks good, thank you for doing that, can you please resolve the conflicts, so we changed the root folder name from`app` to `experimenter`, that's why you are seeing this conflict, kindly please resolve this, I can take look again then.

**Comment by emmaz12** [comment]
@yashikakhurana I am having problems with renaming the root directory which caused numerous issues to arise. Just updated my fork to reflect the correct directory names from app to experimenter. Planning on creating new PR to resolve conflicts.

**Comment by yashikakhurana** [comment]
> @yashikakhurana I am having problems with renaming the root directory which caused numerous issues to arise. Any suggestion
since you have one line change, quickest soltuion, go to main, pull new changes and create new PR, second method requires renaming and then pushing

**Comment by emmaz12** [comment]
@yashikakhurana Will do. Should I go ahead and close this PR then?

**Comment by yashikakhurana** [comment]
> @yashikakhurana Will do. Should I go ahead and close this PR then?

yes goa ahead please

**Pull request closed without merging**
