### PR TITLE
fix(nimbus): Infrequent non-default windows users; increment build ve…

### PR DESCRIPTION
**Pull request by piatra**
…rsion

### CODE REVIEW

**Comment by piatra** [comment]
Another one for you @jaredlockhart thanks 😁

**Review by lmorchard — APPROVED** [review]
LGTM insofar as tests pass and JEXL validation seems happy

**Comment by jaredlockhart** [comment]
@piatra One thing that I'm curious about is whether modifying targeting configurations in place will inadvertently or adversely other experiments which may also be using them.  If only one body of experiments uses them then it's probably fine but I'm curious if we might in the future see cases where one team modifies a targeting configuration and accidentally disrupts the experiments of another.

**Comment by piatra** [comment]
I think you're right and targeting expressions should never update (unless a bug is found maybe) from their original usecase.
This one that I've changed here has never been in use yet and these updates are the result of the review and QA process.

**Pull request merged**
