### PR TITLE
fixes #3972 feat(nimbus): add handy links to header when in summary view

### LINKED ISSUE #3972: Add links on Summary page
We should add a "Back" or "Experiments" link on the Summary page.

Also, if the experiment is in "draft" status, we should have a link to edit the experiment. 

If it's in "Review," it might make sense to link to the request review page. Check with Ana/Kate on status and expected links based on status.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-582)
┆Issue Number: EXP-582

### PR DESCRIPTION
**Pull request by jodyheavener**
Closes #3972

This PR adds some handy links to the header of an experiment's summary page.

- Link to go "Back to Experiments".
- Links to go to "Edit Experiment" / "Go to Review" / "Go to Design" depending on experiment state.

[Storybook preview.](https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/171d49e2bbc69ae75593ee0c2d91785e1b2368c8/nimbus-ui/index.html?path=/story/components-headerexperiment-summary-view--status-draft)

Screenshots:

Screen Shot 2021-02-02 at 11 36 41 AM
Screen Shot 2021-02-02 at 11 36 01 AM
Screen Shot 2021-02-02 at 11 29 50 AM

### CODE REVIEW

**Comment by LZoog** [comment]
Daaaang, @jodyheavener, I just realized that with the decision to combine the Design/Summary pages that we learned about today, we wouldn't need this, but it looks so nice😅

**Comment by jodyheavener** [comment]
Oof, you are correct. Oh well! Thanks for catching.

**Comment by jodyheavener** [comment]
Ana has cleared this to be temporarily merged and we can remove it when we combine the Summary page.

**Review by LZoog — APPROVED** [review]
LGTM. There's a nit or two I could've maybe added but I don't think they're worth addressing since we'll remove this later. Probably good to link to this issue in the issue for combining Design/Summary pages for reference for when we do remove this, but I think this is a _fantastic_ solution until we get there and users will dig it. 😁

**Pull request merged**
