### PR TITLE
fixes #8500

### LINKED ISSUE #8500: Replace constants
`NimbusExperiment` model inherits `NimbusConstants` 
``` python class NimbusExperiment(NimbusConstants, TargetingConstants, FilterMixin, models.Model):```

 https://github.com/mozilla/experimenter/blob/86c4d1d7e8c9ab20d1a5d07568cb542655238266/experimenter/experimenter/experiments/models.py#L109

so essentially you can on Nimbus experiment model like this `self.Application.DESKTOP` like here- https://github.com/mozilla/experimenter/blob/86c4d1d7e8c9ab20d1a5d07568cb542655238266/experimenter/experimenter/experiments/models.py#L287
so that means instead of writing `NimbusConstants.Application.Desktop`, you can write `NimbusExperiment.Application.Desktop` there are many place where we can replace constants with NimbusExperiment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3278)

### PR DESCRIPTION
**Pull request by cherish2003**
Because
- Replacement of constants

This commit

- Replaces NimbusConstants with NimbusExperiment

### CODE REVIEW

**Comment by cherish2003** [comment]
@yashikakhurana i have done changes as mentioned in this issue but i wan unable to know why this checks are failing ? can you kindly explain

**Comment by cherish2003** [comment]
@yashikakhurana the failing test is mentioned not required so i am thinking no need of any changes

**Review by yashikakhurana — CHANGES_REQUESTED** [review]
Unfortunately, this is not a valid change, if you will refer to the issue it says you have to refactor `NimbusConstants.Application` to `NimbusExperiment.Application....`

**Comment by cherish2003** [comment]
@yashikakhurana can you elaborate more and explain what changes to be made

**Comment by yashikakhurana** [comment]
@cherish2003 like here https://github.com/mozilla/experimenter/blob/1ff945fbffe99f63c64cb5772e5347455efe3c6d/experimenter/experimenter/experiments/tests/test_models.py#L740 we are using `NimbusContants`, but we can use `NimbusExperiment`

**Comment by cherish2003** [comment]
@yashikakhurana in what specific files this changes are required to be made

**Comment by yashikakhurana** [comment]
@cherish2003 there are lot of places, you have to find out, I am closing this PR for now, feel free to open new PR with you changes

**Pull request closed without merging**
