### PR TITLE
fixes #8246 refactor(project): change changed_on to updated_date_time…

### LINKED ISSUE #8246: Use updated_date_time instead of changed_on
We can use the new `-_updated_date_time` instead of `-changed_on`. Change all of the models and tests to match.

example: https://github.com/mozilla/experimenter/blob/29986536ccb52fa9390e2d041f360dda277b13e2/app/experimenter/experiments/models.py#L68

_Originally posted by @yashikakhurana in https://github.com/mozilla/experimenter/pull/8235#discussion_r1096123714_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3128)

### PR DESCRIPTION
**Pull request by 0x0god**
… in all models and tests to match

Because

-  There are two different models. -changed_on is on the NimbusChangeLog model, whereas -_updated_date_time is on NimbusExperiment.

This commit

- change "-changed_on" to "-_updated_date_time" in all models and tests

### CODE REVIEW

**Comment by yashikakhurana** [comment]
@0x0god can you check some of your test cases are failing

**Comment by yashikakhurana** [comment]
and you have to run the command `make generate_types`

**Comment by 0x0god** [comment]
Thanks for the tip @yashikakhurana , yes seen, working on that...

**Comment by 0x0god** [comment]
> @0x0god you can test your project locally, before pushing the changes, `make check` command

Noted….trying to fix the docker command on my windows 10 wsl2 atm….will do that asap. Thanks

**Pull request closed without merging**
