### PR TITLE
chore(deps): fix Storybook builds by completing other upgrades

### PR DESCRIPTION
**Pull request by lmorchard**
~Opening as a draft as I poke it with a stick and see what exactly is breaking.~ Now with a real commit message:

Because:

* a partial upgrade of dependencies caused broken Storybook builds

This commit:

* completes upgrades of other dependencies, which appears to fix things

### CODE REVIEW

**Comment by lmorchard** [comment]
Narrowing it down to just `@storybook/react` at 6.2.9 as breaking things?

Reverting just that upgrade seems to get it back to working:

https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/4906234d2f37f8841f8929de7ce2b647fc74ef61/index.html

**Comment by lmorchard** [comment]
Yup, upgrading `@storybook/react` causes breakage

https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/5674b63d03772fdc351db283d9929764bc36bfec/nimbus-ui/index.html

**Comment by lmorchard** [comment]
Manage to reproduce breakage locally, then tried bisecting `@storybook/react` versions between 6.1.21 and 6.2.9

Looks like whatever happened, it happened with 6.2.0-alpha.7

**Comment by lmorchard** [comment]
Oh yeah, and slightly more detailed errors here locally - but none apparently within our own components?

**Comment by lmorchard** [comment]
Possibly related to this old issue?

https://github.com/storybookjs/storybook/issues/14214

**Comment by lmorchard** [comment]
An interesting thing: our react-dom was at v16.13.1 - that should be upgraded in sync with react to 17.0.2

**Comment by lmorchard** [comment]
Hmm, it's possible that upgrading react-dom has fixed the storybook build?

https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/f7545b5ae371a1283540b2cb8becab801b191313/nimbus-ui/index.html?path=/story/components-apperroralert--basic

**Comment by jodyheavener** [comment]
@lmorchard feel free to drop this commit if this doesn't end up being helpful, but looks like some other upgrades got those tests passing again 🤘

**Comment by lmorchard** [comment]
Squashed, rebased against main, let's see what this does!

**Review by jodyheavener — APPROVED** [review]
works for me :)

**Comment by lmorchard** [comment]
Oh yeah, I forgot to take this out of draft. Let's ship it

**Pull request merged**
