### PR TITLE
fix #3549 feat(nimbus): add Probe and ProbeSet

### LINKED ISSUE #3549: Add ProbeSet and Probe models
In order to deprecate "features" in the shared repo, we should create ProbeSet and Prob models. Please refer to this ER diagram: [https://docs.google.com/document/d/16ekd-cXkJF8_UTgkZ3ufzJFusYz9htd5EE2NpIFFJp4/edit#](https://docs.google.com/document/d/16ekd-cXkJF8_UTgkZ3ufzJFusYz9htd5EE2NpIFFJp4/edit#)

ProbeSet

* name (str)
* description (text)

Probe

* ProbeSet (fk)
* kind: "event" | "scalar"
* name: (str)
* event_category: string;
* event_method?: string;
* event_object?: string;
* event_value?: string;

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-353)
┆Issue Number: EXP-353

### PR DESCRIPTION
**Pull request by jaredlockhart**
Because

* We want to store telemetry probe information so jetstream can analyze Nimbus experiments

This commit

* Adds Probe and ProbeSet models
* Adds them to the admin
* Adds graphql types for them

### CODE REVIEW

**Comment by bbangert** [comment]
This looks fine code-wise, but I'm curious about the problem this is addressing and the manner in which it is handling it. What is this telemetry probe data?

**Review by bbangert — APPROVED** [review]
Looks good, I checked back in the ER diagram to see where this came from.

**Review by emtwo — APPROVED** [review]
Code looks fine to me. I just want to make sure I'm understanding the semantic implications correctly.

It seems that we are just renaming a "feature" to be a "probe set" which just means that a feature is defined by a set of probes. Kind of already how it's been represented before, just more clear naming.

**Comment by jaredlockhart** [comment]
Yep exactly, it's this:

https://github.com/mozilla/nimbus-shared/blob/main/types/features.ts#L1-L31

but renaming `Feature` to `ProbeSet` and `FeatureEventTelemetry` to `Probe` and storing it in the Experimenter database instead of constants in the shared repo.

**Pull request merged**
