### PR TITLE
issue #4289: progress on per-field review error icons for branch forms

### PR DESCRIPTION
**Pull request by lmorchard**
Opening initially as a draft so I can get a Storybook build to share around. Not entirely sure this is how we want the review feedback UI to work.

Also need to rework tests on both server and client side, but wanted to hold off on that until after getting some eyes on the UI.

### CODE REVIEW

**Comment by lmorchard** [comment]
Some relevant storybook links from the initial push:
* https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/ba313db52c91e9e65cc23f8775025bad3b264f72/nimbus-ui/index.html?path=/story/components-formbranches-formbranch--with-review-error-missing-control-branch
* https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/ba313db52c91e9e65cc23f8775025bad3b264f72/nimbus-ui/index.html?path=/story/components-formbranches-formbranch--with-review-errors
* https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/ba313db52c91e9e65cc23f8775025bad3b264f72/nimbus-ui/index.html?path=/story/components-formbranches--with-review-errors

**Comment by lmorchard** [comment]
Probably my main head-scratching thing is - we have client-side validation errors, server-side on-submit validation errors, and final review errors. Maybe we want all those to look the same? Right now, the "missing info" icon presentation for review errors differs:

Capture

**Comment by k88hudson** [comment]
I like it! I tried writing some "UX docs" here on the client/server/

https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/a57a8d99fdd036552dcb3941cb7a9c2273bdcebd/nimbus-ui/index.html?path=/story/docs-form-validation--client-side-validation

I just suggested maybe marking that "required for launch" error type with just some help text, but I like your icon too

**Comment by jodyheavener** [comment]
I’m all for making the “missing info” presentation look like the “submit error” presentation. This makes them visually consistent, but it also solves the issue of someone needing to hover over the missing info icon to see the error (they may not know to do that and it could be confusing). @AnaMedinac what do you think?

**Comment by AnaMedinac** [comment]
Agreed, I like the consistency of making both errors look the same. Also, if this removes the need for hovering even better; I haven't really noticed anyone using the concept of hovering anything to find more info during user testing.

**Comment by lmorchard** [comment]
> I just suggested maybe marking that "required for launch" error type with just some help text, but I like your icon too

FWIW, that icon isn't new with this PR, it's what we're using on other pages. This PR was just meant to bring branches more in line with what we're doing elsewhere

> I’m all for making the “missing info” presentation look like the “submit error” presentation.

If this is what we want to do, then I should close the PR and move review errors into the same feedback style as submit errors. We'll need to do that on the rest of the forms, too

**Comment by LZoog** [comment]
+1 on making these look like the submit errors.

Probably known by everyone commenting here but this is what you'll see when you click on "Missing details in: [page link]" and we have them set up I believe on all pages except for branches.

**Comment by LZoog** [comment]
Related: #4291

**Comment by lmorchard** [comment]
Just going to close this PR - it isn't the approach we want to take, UX-wise.

**Pull request closed without merging**
