### PR TITLE
fix #7366 feat(nimbus): Hide end enrollment option

### LINKED ISSUE #7366: The “End Enrollment for Experiment”  button is still displayed for an experiment with “End Experiment” requested
**[Prerequisites]:**

* Have a Live experiment with Enrollment enabled.

**[Steps to reproduce]:**

1. Have someone else click the “End Experiment” button for the experiment from prerequisites.
1. Approve the change from the experiment’s page.
1. Observe the page.

**[Expected result]:**

* The “End Enrollment for Experiment” button is no longer displayed.

**[Actual result]:**

* The “End Enrollment for Experiment” button is displayed.

**[Notes]:**

* The issue is not reproducible the other way around. The “End Experiment” button is not displayed if enrollment has been requested.

* Clicking the “End Enrollment for Experiment” button will display an error message and will not otherwise affect the experiment.

* Attached are screenshots of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2493)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24655">clicking the button.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24656">end button.png</a>

### PR DESCRIPTION
**Pull request by yashika-khurana**
Because

* We still see the option to end enrollment even though the experiment is ended and approved

This commit

* Removes the option to `End enrollment for the experiment` and a test case to verify new changes
image

fix #7366

### CODE REVIEW

**Comment by jaredlockhart** [comment]
Ah it vanished:

Screen Shot 2022-07-20 at 10 57 44 AM


And then came back:
Screen Shot 2022-07-20 at 10 58 00 AM


The 'End Experiment' and 'End Enrollment' buttons should only appear if publish_status==IDLE

**Review by eliserichards — COMMENTED** [review]
This is looking good to me, but I'm not 1000% certain that I haven't missed a state 😅 Leaving the official ✅ for @jaredlockhart

**Comment by jaredlockhart** [comment]
@eliserichards @yashika-khurana Don't we still need to make a change after the last time we tested it last week?  To make the buttons only show on `Idle`?

**Comment by yashika-khurana** [comment]
> @eliserichards @yashika-khurana Don't we still need to make a change after the last time we tested it last week? To make the buttons only show on `Idle`?

@jaredlockhart its still in progress, I will update this today, just finishing off other tasks :)

**Review by jaredlockhart — APPROVED** [review]
Yes! Works perfectly thank you @yashika-khurana ! 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
