### PR TITLE
fix #7731 feat(nimbus): More info on tabs

### LINKED ISSUE #7731: Add more info on other tabs
Since we have added more info on landing page in this ticket- [https://mozilla-hub.atlassian.net/browse/EXP-2704](https://mozilla-hub.atlassian.net/browse/EXP-2704|smart-link) , these changes are only implemented for the live tab, we would like to add all this info for all the tabs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2772)

### PR DESCRIPTION
**Pull request by yashika-khurana**
Because

* Since we have added more info on the landing page,  those changes were only implemented for the live tab, we would like to add all this info for all the tabs

This commit

* Adds `application`, `channels`,`firefox min version`, `firefox max version` and `population percent`, `start`, `end` and `enroll` to other tabs i.e. `draft`, `completed`, `review`, `preview`, and `archived` and test cases to verify new changes

fix #7731 
screenshot of changes:
image

### CODE REVIEW

**Review by jaredlockhart — CHANGES_REQUESTED** [review]
Awesome, looks great, just one thing, how come on Completed it looks more squashed than Live even though it has one less column?  Is there any way to fix that?

Screen Shot 2022-09-13 at 4 42 16 PM
Screen Shot 2022-09-13 at 4 42 25 PM

**Comment by yashika-khurana** [comment]
@jaredlockhart fixed, here are updated screenshot
Screen Shot 2022-09-13 at 2 00 50 PM
Screen Shot 2022-09-13 at 2 00 42 PM

**Comment by yashika-khurana** [comment]
also, this new change removes this extra spacing 
image
image

**Comment by jaredlockhart** [comment]
Just complete sidebar, this has always bothered me:

Screen Shot 2022-09-13 at 5 16 41 PM

**Comment by yashika-khurana** [comment]
> Just complete sidebar, this has always bothered me:
> 
> Screen Shot 2022-09-13 at 5 16 41 PM

I am so sorry I think I am not sure what you mean :(

**Comment by yashika-khurana** [comment]
oh do you mean `Results` title is not showing up in blue?

**Review by jaredlockhart — CHANGES_REQUESTED** [review]
Oh I see, we got lost in communication.  I didn't want the new fields added to the other tabs, I wanted the same info on every tab 🙏

**Comment by jaredlockhart** [comment]
> oh do you mean `Results` title is not showing up in blue?

I mean every column title is a blue clickable link except `Results` which is black, becuase you can't sort by results, but also the link to the results page is a blue link that says `Results` on every row, so it's just very visually confusing.  It's not a big deal, we can deal with it later when we improve the layout of the table, it's fine for now.

**Comment by yashika-khurana** [comment]
oh, my thought is this: 
since when the experiment is in review/preview/draft state we can skip columns like `start date`, `enrolling period` and `end date`. I can add those fields just my concern is if it's worth it too add that info on that particular tabs
I am open to any suggestions 🤔 @jaredlockhart 🙏

**Comment by yashika-khurana** [comment]
also, I think we should add the `Enrolling column` on the completed tabs, in this way both live and complete will have same info

**Comment by jaredlockhart** [comment]
@yashika-khurana Yeah so just capturing what we said earlier, let's have all the columns on every tab and just fill in `N/A` in the date fields where there is no date.

**Review by jaredlockhart — APPROVED** [review]
Yes fantastic.  Greatly simplifies the code, makes all the tabs more usable, the `Not Set` is a very nice touch.  Showing `N Days` for enrollment where we know the days but not the dates is also a very nice touch.  Great job @yashika-khurana 👏 👏 👏 👏 👏 👏

**Pull request merged**
