### PR TITLE
Issue 4846 - Add a CODEOWNERS file.

### LINKED ISSUE #4846: Add a CODEOWNERS file to auto assign reviewers based on globs?
Re:reviewers, what about using a CODEOWNERS file to auto assign reviewers based on globs? 
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

For example, Tim+Anna are reviewers for any jetstream changes, experimenter core can be reviewed by whomever adds themselves to the codeowners file for whatever paths they volunteer to review/own. I can review PRs that add .svg files.

if we add e2e testing docs, B4hand and I can be notified on changes in those paths.

_Originally posted by @pdehaan in https://github.com/mozilla/experimenter-docs/issues/8#issuecomment-797820943_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1083)
┆Issue Number: EXP-1083

### PR DESCRIPTION
**Pull request by jrbenny35**
Closes #4846

### CODE REVIEW

**Comment by jrbenny35** [comment]
Do we want to make this more complete?

**Comment by pdehaan** [comment]
Nit: Maybe move this into .github/ directory to keep the root folder a bit more... empty.

> To use a CODEOWNERS file, create a new file called `CODEOWNERS` in the root, `docs/`, or `.github/` directory of the repository, in the branch where you'd like to add the code owners.

&mdash; via https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location

Otherwise, I think this is a great start. Any other test-thusiasts are welcome to add their GitHub names to be added as a auto-reviewer to an arbitrary path.
For example, if you only care about Nimbus (and not legacy) integration tests, you can subscribe to only [app/tests/integration/nimbus](https://github.com/mozilla/experimenter/tree/main/app/tests/integration/nimbus).

**Review by pdehaan — APPROVED** [review]
Lovin it!
I'll let @jaredlockhart give the final 👀 and the honour of pressing the green button.
Then once this lands we can push a minor change to a test file (extra space or comment) and confirm the plumbing works for the app/tests directory. Huzzah!

**Comment by lmorchard** [comment]
Hmm, Jared's out and I think we want to build on top of this with some more code owners. I'll just go ahead and hit the button

**Comment by jaredlockhart** [comment]
@jrbenny35 Thanks for adding this and thanks @pdehaan and @lmorchard for hopping on to review! 🎉

**Pull request merged**
