### PR TITLE
fixes 8246 refactor (nimbus):  change changed_on to updated_date_time

### PR DESCRIPTION
**Pull request by kennedy-muthaura**
Because
we are required to use updated_date_time instead of changed_on

This commit

changes all the  references of changed_on to updated_date_time
two tests are failing at the end  
FAILED experimenter/experiments/tests/api/v5/test_queries.py::TestNimbusExperimentBySlugQuery::test_get_experiment_by_slug_returns_experiment_data_00

### CODE REVIEW

**Comment by yashikakhurana** [comment]
@kennedy-muthaura thank you for working on this, but the task was not about renaming the field of the Changelog model, for more explanation refers to this link- https://github.com/mozilla/experimenter/issues/8246#issuecomment-1457153025 let me know if you any questions. thanks

**Comment by yashikakhurana** [comment]
@kennedy-muthaura are you still working on this? let me know if you need help

**Comment by yashikakhurana** [comment]
@kennedy-muthaura if you will refer to this function- https://github.com/mozilla/experimenter/blob/097f11ed9a638d42e5bfefd88a0e9d6b6c500d7d/experimenter/experimenter/experiments/models.py#L54, it uses changes__changed_on to return the sorted results based on the changes from NimbusChangelogManager- here https://github.com/mozilla/experimenter/blob/097f11ed9a638d42e5bfefd88a0e9d6b6c500d7d/experimenter/experimenter/experiments/models.py#LL1040C6-L1040C30  , but recently we added one field in the `NimbusExperiment `Model called `_updated_date_time`, so now instead of using changelog manager model to fetch the latest updated, we can use `_updated_date_time` here https://github.com/mozilla/experimenter/blob/097f11ed9a638d42e5bfefd88a0e9d6b6c500d7d/experimenter/experimenter/experiments/models.py#L54,

**Comment by kennedy-muthaura** [comment]
> 

okay..    let  me change that

**Comment by kennedy-muthaura** [comment]
> > 
> 
> okay.. let me change that



> Is this only  function that needs to be updated ?

**Pull request closed without merging**
