### PR TITLE
fix #7029 bug(nimbus): handle zero or none in jetstream data

### LINKED ISSUE #7029: Experimenter occassionally not showing most recent results
We had a few instances where Experimenter did not show the most recent results:
* https://mozilla.slack.com/archives/CF94YGE03/p1643415585750689
* https://mozilla.slack.com/archives/CF94YGE03/p1639509842292700?thread_ts=1639507377.290900&cid=CF94YGE03

Jared mentioned that there might be issues during the parse stage:
https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/13473945/?query=is%3Aunresolved
https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/11763102/?query=is%3Aunresolved

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2166)

### PR DESCRIPTION
**Pull request by jaredlockhart**
Because

* Jetstream may output zero or None for certain numerical fields
* The Experimenter Jetstream parser should be resilient when encountering those values

This commit

* Adds test cases including jetstream returning all zeros or all None
* Updates the parse logic that was breaking when encountering those values

### CODE REVIEW

**Review by scholtzan — APPROVED** [review]
As far as I can tell this looks good. Not super familiar with the test setup here, but reading through it it it made sense

**Comment by jrbenny35** [comment]
@jaredlockhart mind explaining exactly what did patch does? That would help me a lot. Thanks.

**Comment by jaredlockhart** [comment]
@jrbenny35 Yep totally.  So the errors we see in sentry here:

https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/13473945/?query=is%3Aunresolved
https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/11763102/?query=is%3Aunresolved

are about the jetstream parser choking when it tries to divide by 0 (an exception in Python) or encounters None where it expects a number.

So this patch adds test cases to replicate that by setting all the input data to either 0 or None, which triggers the same failures we see in sentry, and then adds checks around to those failures to prevent them.  

Does that help?

**Comment by jrbenny35** [comment]
Thanks @jaredlockhart !

**Pull request merged**
