### PR TITLE
fix(project): code format & generate types

### PR DESCRIPTION
**Pull request by jodyheavener**
Looks like we needed a code_format and generate_types

### CODE REVIEW

**Review by jaredlockhart — COMMENTED** [review]
Oh thanks for catching this @jodyheavener but we need to actually fix this or it'll just happen again, ticket here: https://github.com/mozilla/experimenter/issues/5038

**Comment by jodyheavener** [comment]
@jaredlockhart Totally but can we manually update it until then? Just want to avoid a larger than necessary diff 😀

**Comment by jaredlockhart** [comment]
But without fixing it, this pr accomplishes nothing?

**Review by jaredlockhart — APPROVED** [review]
Nvm let's just land it 👍

**Comment by jodyheavener** [comment]
@jaredlockhart I mean, it allows other PRs to be opened and merged without creating unnecessarily larger diffs?

**Comment by jaredlockhart** [comment]
This might not rebased on latest main with the new circle definitions

**Pull request merged**
