### PR TITLE
added react-bootstrap fixes #2942

### LINKED ISSUE #2942: Use React-Bootstrap for Rapid UI
We've used React-Bootstrap successfully for our old UI and it does a lot of things for us in terms of consistent design and layout, I'd like to use them for the Rapid UI as well.

### PR DESCRIPTION
**Pull request by tiftran**
Decided to leave the form/inputs alone since, it seems like we might be changing that....

### CODE REVIEW

**Comment by jaredlockhart** [comment]
@tiftran could you pls also do all the `col`/`row` divs into `Col`/`Row` 🙏

**Comment by tiftran** [comment]
@jaredlockhart yup, for sure. Missed that.

**Comment by jaredlockhart** [comment]
I guess this is blocked on that TS dependency issue with popper.  I'd like to be able to do this but I'm not sure what the solution is.  @rehandalal If you get some spare cycles could you see if you can find a quick solution?  If not then I guess we table this and reconsider it later.

**Comment by jaredlockhart** [comment]
Let's revisit this in a few weeks when we can have a broader discussion about how we want to structure the frontend.

**Pull request closed without merging**
