### PR TITLE
fix #7766 nimbus(chore): Update integration test ping server for Mobile clients

### LINKED ISSUE #7766: Update integration test ping server to allow for Mobile clients
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2810)

### PR DESCRIPTION
**Pull request by jrbenny35**
Because
* Our current implementation of the Ping server used to capture telemetry is quite specific to Desktop clients

This Commit
* Expands the implementation to allow for both Desktop and Mobile clients to submit pings to the server.

### CODE REVIEW

**Review by yashika-khurana — COMMENTED** [review]
Can you help me gain more context about ping and its use of it here, and how it gonna be helpful for mobile applications, I think I am missing context 🤔

**Comment by jrbenny35** [comment]
> Can you help me gain more context about ping and its use of it here, and how it gonna be helpful for mobile applications, I think I am missing context 🤔

Sure thing. So when we do our telemetry integration tests, specifically the tests in [here](https://github.com/mozilla/experimenter/blob/main/app/tests/integration/nimbus/test_mobile_integration.py), we collect telemetry to verify it. The current ```ping_server``` only has a route for desktop pings, this PR will change it to allow for both Desktop and Mobile clients to submit to the same route. I plan to add integration tests for Mobile clients in the future so this just gets the ping server setup for that.

**Review by yashika-khurana — APPROVED** [review]
thanks @jrbenny35 for explaining it, it makes more sense to me 🎉

**Review by jaredlockhart — APPROVED** [review]
Yep looks good and thank you for the very clear explanation 👍

**Pull request merged**
