### PR TITLE
Strip obsolete '.value' from Python enums

### PR DESCRIPTION
**Pull request by lennartschoch**
As this was requested in issue #6068, I used some RegEx magic to remove the trailing `.value` from enum lookups.

### CODE REVIEW

**Comment by lennartschoch** [comment]
I am suddenly getting some formatting issue on my machine.
Will investigate whether it could be related and move the PR out of draft mode afterwards

**Comment by jaredlockhart** [comment]
@lennartschoch If it's about code formatting you can run `make code_format` and it'll reformat everything and then `make check` might pass.

**Comment by jaredlockhart** [comment]
Also I have to figure out how to get Circle to run the tests for this PR....

**Comment by lennartschoch** [comment]
Thanks for the advice @jaredlockhart ! I fixed it manually before I could see your comment, but will keep it in mind for the future.

For some reason, eslint still fails somewhere inside `nimbus-ui` on my machine, but this happens even on the `main` branch, so should not be related and hopefully CircleCI will run just fine. I might open an issue once I get to the bottom of this.

**Comment by jaredlockhart** [comment]
@lennartschoch Oh interesting, it should be identically locally and CI since they both just run `make check` and the versions are locked in the lockfiles.....  So if you're seeing something different then we've done something wrong.  If you see a test failure just file it as a ticket and include the output of the test failure and we can see if we can reproduce it.  It might also be intermittent (ie if you run the tests again and it passes) in which case it's definitely just a bug in the test.

**Comment by lennartschoch** [comment]
@jaredlockhart Interestingly, I don't get any information about the cause of the failure, just the exit code of the command (137). I'll see whether I can tweak the verbosity and get some more context.

**Comment by jaredlockhart** [comment]
@lennartschoch What version of Docker/Docker for Desktop are you using?

**Comment by lennartschoch** [comment]
@jaredlockhart I am using Docker for Desktop 3.5.2.18 on macOS Big Sur.

**Comment by jaredlockhart** [comment]
OH @lennartschoch sorry, I need to update the instructions.  The node tasks take too much memory and the default settings have the vm very restricted.  You should set your Docker resources to:

CPU: Max
Ram: 50% of whatever your system has
Swap: Max
Disk: 100gb+

**Comment by jaredlockhart** [comment]
Reasons for 'Out of memory' error 137 in Docker

    Docker container has run out of memory.

**Comment by lennartschoch** [comment]
@jaredlockhart oh of course, 137 means `out of memory`. Should have checked the meaning of the exit code, sorry!🤦‍♂️ Increasing the memory in Docker Desktop fixed it for me, all tests run fine now!

**Comment by jaredlockhart** [comment]
@lennartschoch Okay I found something hidden deep in the docs that might help:

```
Note: If a user submits a pull request to your repository from a fork, but no pipeline is triggered, then the user most likely is following a project fork on their personal account rather than the project itself of CircleCi, causing the jobs to trigger under the user's personal account and not the organization account. To resolve this issue, have the user unfollow their fork of the project on CircleCI and instead follow the source project. This will trigger their jobs to run under the organization when they submit pull requests.
```

So see if you can go into circleci, unfollow your fork, and then follow this repos circle builds?

**Comment by lennartschoch** [comment]
@jaredlockhart Unfortunately, following this repo on CircleCI didn't help (I wasn't following my fork in the first place). According to the [CircleCI docs](https://circleci.com/docs/2.0/oss/), PRs from forked repos are not being built by default:

```
Build pull requests from forked repositories

Many open source projects accept PRs from forked repositories. Building these PRs is an effective way to catch bugs before manually reviewing changes.

By default, CircleCI does not build PRs from forked repositories. To change this setting, go to the Project Settings>Advanced of your project and set the Build forked pull requests option to On.
```

Could you maybe try to enable that setting?

**Comment by jaredlockhart** [comment]
@lennartschoch That setting was already enabled, but something must have worked becuase now they ran and completed!  This should be mergeable now, thank you! 🎉

**Comment by jaredlockhart** [comment]
I'll merge this and format the commit [according to the contributing guidelines](https://github.com/mozilla/experimenter/blob/main/contributing.md#git-commit-guidelines) but if you can pls review the commit formatting for future prs 🙏

**Review by jaredlockhart — APPROVED** [review]
🎉 🎉 🎉

**Comment by lennartschoch** [comment]
> @lennartschoch That setting was already enabled, but something must have worked becuase now they ran and completed! This should be mergeable now, thank you! 🎉

Not 100% sure what triggered the pipeline, but somehow it started running when I merged `main` into this branch :)



> I'll merge this and format the commit [according to the contributing guidelines](https://github.com/mozilla/experimenter/blob/main/contributing.md#git-commit-guidelines) but if you can pls review the commit formatting for future prs 🙏

Thanks for the hint, will pay attention to this in the future!

**Pull request merged**
