### PR TITLE
Added link for creating a new github issue in this repo under "help" section.

### PR DESCRIPTION
**Pull request by prernadabi23**
fixes https://github.com/mozilla/experimenter/issues/7803
fix(nimbus): Added link for creating a new GitHub issue in this repo under the "help" section
I have added the GitHub svg file, added an external link, and all as per the instructions given.
Please review it.
@yashika-khurana
@shell1

### CODE REVIEW

**Comment by prernadabi23** [comment]
@yashika-khurana All checks passed 😭.

**Comment by yashikakhurana** [comment]
@prernadabi23 that's so awesome, can you also rebase your main, FYI- we renamed `app` root folder to `experimenter`, let me know if you need help, thanks

**Review by yashikakhurana — COMMENTED** [review]
it looks good, thank you @prernadabi23 you did it ❤️ , the only thing left is to rebase your PR

**Comment by prernadabi23** [comment]
@yashikakhurana Is this how it needs to be done? I am a little confused.

**Review by yashikakhurana — CHANGES_REQUESTED** [review]
@prernadabi23 thank you and great job having everything set up too :), In your PR I see two .svg file, not sure why, but we just need one image and can work with that, also the image is not complete we are only seeing one quadrant of the image, kindly fix it and let me know if you have any questions :) 
image

**Comment by prernadabi23** [comment]
@yashikakhurana sorry for the silly mistake. I did the changes required.

**Comment by prernadabi23** [comment]
@yashikakhurana Thank you so much! I learned a lot in this process and would love to contribute more :)

**Pull request merged**
