### PR TITLE
Fix startup for local development

### PR DESCRIPTION
**Pull request by leplatrem**
Main change concerns default port 4433 instead of 443.

f?

### CODE REVIEW

**Comment by leplatrem** [comment]
I'm also having CSRF errors on experiment submit with the sample env/settings

I tried this without success:
```py
CSRF_TRUSTED_ORIGINS = [HOSTNAME]
```
So I ended up disabling the middleware to go on hacking...

**Comment by jaredkerim** [comment]
@leplatrem What is the reason for switching from 443 to 4433?

**Comment by leplatrem** [comment]
> @leplatrem What is the reason for switching from 443 to 4433?

Because ports below 1024 are privileged... it's quite common to avoid do local dev on 80/443, no?

**Comment by jaredkerim** [comment]
@leplatrem I think I originally set it to 443 becuase when I was testing against Auth0/OpenIDC in dev they didn't support custom ports, but now that that's over I don't see any reason why we can't use any arbitrary port, but I'd rather make make it configurable.  

See if there's a way you can put the port in the ENV file and then refer to it in the compose file this way: https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by jaredkerim** [comment]
@leplatrem Do you still want to try to change the port or should we close this?

**Comment by leplatrem** [comment]
I don't care too much. You can close if you're not convinced, I'll manage something out (and re-open one PR if it needs to become configurable)

**Comment by jaredkerim** [comment]
@leplatrem Okay I will close this and we can revisit if it becomes a problem in the future.

**Pull request closed without merging**
