### PR TITLE
feat(cirrus): Send preview flag in telemetry data

### LINKED ISSUE #11227: Update cirrus telemetry to include that flag
We should be able to separate out the enrollments which are done by QA (i.e preview mode used), Add the information in ping so that we can separate that out during the analysis

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4663)

### PR DESCRIPTION
**Pull request by yashikakhurana**
Because

- We have added the support so that QA can use preview mode and can do the enrollment

This commit

- Adds the information in the telemetry if its a preview mode enrollment

Fixes #11227

### CODE REVIEW

**Review by jaredlockhart — APPROVED** [review]
Very nice 👍

**Comment by yashikakhurana** [comment]
# Request for data collection review form

1) What questions will you answer with this data?
How to check if enrollment done on web apps is using the preview mode or not?

2) Why does Mozilla need to answer these questions? 
This data will help us to see if the enrollment is related to the preview mode

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
None, no solution is sufficient unless the data collected as we don't have any way to link if enrollment is linked to preview mode

4) Can current instrumentation answer these questions?
No

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>is preview mode</td>
    <td>Technical data</td>
    <td>https://mozilla-hub.atlassian.net/browse/EXP-4663</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
The documentation can be found in the proposal document linked in the ticket above (internal only), the [metrics.yaml](https://github.com/mozilla/experimenter/pull/11228/files#diff-b9fd03d18c4e352ceb4840d88c7649d82094d13a4d8d2d7483803401fe85971d) on this PR, and the [Glean dictionary](https://dictionary.telemetry.mozilla.org/).

7) How long will this data be collected?  Choose one of the following:
* I want to permanently monitor this data.
      - ykhurana@mozilla.com
      - chumphreys@mozilla.com
      - jkerim@mozilla.com
      - project-nimbus@mozilla.com

8) What populations will you measure?
All consumers of the Cirrus

9) If this data collection is default on, what is the opt-out mechanism for users?
By default is sends the false as a value, will only send if its true

10) Please provide a general description of how you will analyze this data.
We'll analyze it in Jetstream

11) Where do you intend to share the results of your analysis?
Mozilla internal

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
No

data-review? @jeddai

**Comment by jeddai** [comment]
> 9. If this data collection is default on, what is the opt-out mechanism for users?
> By default is sends the false as a value, will only send if its true

This is not a sufficient opt-out mechanism -- please update the review request with something that will prevent _any_ data from being sent. 

data-review-

**Comment by yashikakhurana** [comment]
> > 9. If this data collection is default on, what is the opt-out mechanism for users?
> >    By default is sends the false as a value, will only send if its true
> 
> This is not a sufficient opt-out mechanism -- please update the review request with something that will prevent _any_ data from being sent.
> 
> data-review-
@jeddai Updated the comment

**Comment by jeddai** [comment]
# Data Review Form

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 
The documentation can be found in the proposal document linked in the ticket above (internal only), the [metrics.yaml](https://github.com/mozilla/experimenter/pull/11228/files#diff-b9fd03d18c4e352ceb4840d88c7649d82094d13a4d8d2d7483803401fe85971d) on this PR, and the [Glean dictionary](https://dictionary.telemetry.mozilla.org/).

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.
Implementing client will make sure to provide a mechanism, and not to call cirrus server at all if user wants to opt-out

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
- [ykhurana@mozilla.com](mailto:ykhurana@mozilla.com)
- [chumphreys@mozilla.com](mailto:chumphreys@mozilla.com)
- [jkerim@mozilla.com](mailto:jkerim@mozilla.com)
- [project-nimbus@mozilla.com](mailto:project-nimbus@mozilla.com)

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 1, Technical Data

5) Is the data collection request for default-on or default-off?
default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**
yes

8) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**
no

data-review+

**Pull request merged**
