### PR TITLE
For #7479 docs(nimbus): Add new state diagram to kinto readme

### PR DESCRIPTION
**Pull request by eliserichards**
#7479

Because...

* We are going to be fleshing out the "request update" section of the experimenter state machine with rollouts being added

This commit...

* Adds an updated version of the state diagram and descriptions to the `app/experimenter/kinto/` folder
* Adds .xml for this state diagram so that we can easily change/edit it in the future (we used the drawio app on confluence)
* Note: another PR will add the sequence diagrams (#7878)

--------
states-v2

### CODE REVIEW

**Review by jaredlockhart — APPROVED** [review]
Yes this all looks right to me, thank you for updating!  Is there some way to export the diagram in an editable form like some xml thing or something so we can re edit it later if we need to?

**Comment by yashika-khurana** [comment]
@eliserichards thank you it looks good, just one question do we need one arrow between remote settings and experiment publish state?

**Comment by eliserichards** [comment]
> 

Yes! Good point, I forgot to add the `XXX.sequence` to this PR

**Comment by eliserichards** [comment]
> @eliserichards thank you it looks good, just one question do we need one arrow between remote settings and experiment publish state?

I see what you mean, maybe a dotted line like we have above 🤔

**Pull request merged**
