### PR TITLE
Added link for creating a new github issue in this repo under "help" section.

### LINKED ISSUE #7803: Add link for creating a new github issue in this repo under "help" section
link using github icon from help section on the lefthand sidebar on the summary that goes to https://github.com/mozilla/experimenter/issues/new

When people need to request advanced targeting - they need to know to file a ticket in this repo.  Under the feedback link - should have a link for "File targeting criteria request"

common scenarios: 
- need a specific release (nightly build, beta version, or dot release) targeted that isn't offered off the version list by default.
- need advanced targeting that isn't available.

image

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2830)

### PR DESCRIPTION
**Pull request by prernadabi23**
fixes #7803 
fix(nimbus): Added link for creating a new GitHub issue in this repo under the "help" section
I have added the GitHub svg file, added an external link, and all as per the instructions given.
Please review it.
@yashika-khurana 
@shell1

### CODE REVIEW

**Comment by yashikakhurana** [comment]
@prernadabi23 kindly please resolve the conflict issue and fix one of the issue run `make check` to see the issue

**Comment by yashikakhurana** [comment]
@prernadabi23 the conflict issue you are seeing because we change the name of the root directory from `app` to `experimenter`

**Comment by prernadabi23** [comment]
So what do I have to do? There's no error in my implementation right? 
@yashikakhurana How do I pass all checks?

**Comment by yashikakhurana** [comment]
@prernadabi23 run command `make code_format`

**Comment by yashikakhurana** [comment]
please resolve the conflict as well, why you are not able to run make commands, I will suggest use Nimbus outreachy channel to discuss with others

**Comment by yashikakhurana** [comment]
@prernadabi23 do you need any help?

**Comment by yashikakhurana** [comment]
@prernadabi23 no worries, I was just checking in to see if you need any support :)

**Comment by prernadabi23** [comment]
@yashikakhurana I am having issues installing. I need help.

**Comment by yashikakhurana** [comment]
@prernadabi23 what issue you are having? Also do try Nimbus outreachy channel for help

**Comment by prernadabi23** [comment]
@yashikakhurana I have completed the procedure till the 5th step in `contributing.md` but when i `make check` some checks fail.
I tried on nimbus channel, I didn't get a response.

**Comment by yashikakhurana** [comment]
@prernadabi23 would highly suggest first rebase your PR and also run make code_format command, this should solve your issue

**Comment by prernadabi23** [comment]
Screenshot from 2023-03-20 10-13-43

I am not able to @yashikakhurana , Is this the way?

**Comment by yashikakhurana** [comment]
@prernadabi23 in the error message it clearly says docker is not running, start docker first :)

**Comment by prernadabi23** [comment]
@yashikakhurana I did start it, but it's still not working.

**Comment by prernadabi23** [comment]
Mam, Can you please guide me? I still couldn't set it up, I would love to solve more issues.
I tried on the nimbus outreach channel but I didn't get any positive response, I don't even know where I am wrong.

**Comment by yashikakhurana** [comment]
@prernadabi23 please refer to the docker instructions on the docker website, I am not sure which OS you have, would suggest searching for that.

**Comment by yashikakhurana** [comment]
@prernadabi23 if you are stuck let me know, I can close this PR for now

**Comment by prernadabi23** [comment]
@yashikakhurana I am still trying, If I couldn't do it by sunday you may close it.

**Comment by prernadabi23** [comment]
Screenshot from 2023-03-24 02-53-25

I think I am all set 😊 this is the output of `make code_format`.

**Comment by prernadabi23** [comment]
Screenshot from 2023-03-24 11-17-13

I don't know why checks are failing.
@yashikakhurana

**Pull request closed without merging**
