### PR TITLE
fix #7747 bug(nimbus): revert "fix #7599 chore(nimbus): explicitly convert snake to camel case (#7724)"

### LINKED ISSUE #7599: Move camelCase fields from graphql to serializers
The GraphQL framework we are using (Graphene) will automatically convert snake_case fields to camelCase fields, so the fields in the serializer are all in snake_case but are referenced in the frontend by camelCase.  To prepare for removing the GraphQL layer, let’s move the camelcasing back a layer to the serializer layer.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2686)

### LINKED ISSUE #7747: Revert snake/camel case migration
The snake/camel case migration introduced several regressions that weren't caught by any tests.  Let's revert that change, and augment the original change with new test cases to cover all those cases and then reintroduce it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2797)

### PR DESCRIPTION
**Pull request by jaredlockhart**
Because
    
* The snake/camel case change introduced a number of regressions in the Nimbus UI
* This highlights some important gaps in our test coverage
* We can revert the change and then reintroduce it with expanded test coverage that covers the cases caught
    
This commit
* Reverts commit 2b4a58c31122e3fdf968cf7882c38eb64a5c8965
* Updates the tests in b1d117e14a9761bb4426a93dc9aa7aade2f0e73c to revert to snake_case

### CODE REVIEW

**Review by yashika-khurana — APPROVED** [review]
I feel so bad we have to revert this 😢 , I am just wondering if we have gathered/filled all the tickets causing those issues?

**Comment by jrbenny35** [comment]
I get the revert but why is this actually causing failures? We can hardly test this at the moment

**Comment by jaredlockhart** [comment]
@jrbenny35 Well what's interesting is that the change introduced regressions despite our entire test suite passing so this highlights a number of interesting gaps in our test coverage.  But now that we've identified them we can revert this change, address each of those issues and expand our test coverage, and then reintroduce the change more safely.

**Comment by yashika-khurana** [comment]
@jaredlockhart wait we need to fix this test case too https://github.com/mozilla/experimenter/pull/7718/commits/6f5baa8fd35203fe4c1038657d45051353ec8f7c

**Comment by jaredlockhart** [comment]
@yashika-khurana Good catch, updated to include that change 👍

**Review by yashika-khurana — APPROVED** [review]
lets revert it back, thanks @jaredlockhart

**Comment by jaredlockhart** [comment]
Thanks @yashika-khurana !

**Pull request merged**
