### PR TITLE
Make all form fields optional (but required to ship)

### PR DESCRIPTION
**Pull request by jaredkerim**
So this change finally makes all fields optional at form save time, but some fields required to ship an experiment.  Fields that are required are marked in red as `Required`.  I filed https://github.com/mozilla/experimenter/issues/1723 as a follow up after @uhlissuh lands her react stuff.  The required fields on the Overview page are actually required before the initial form can be saved but after that any fields can be filled out in any order.  Here's how it all looks:

Screenshot_2019-10-03 Mozilla Experimenter
Screenshot_2019-10-03 Fields are different
Screenshot_2019-10-03 Fields are different (1)
Screenshot_2019-10-03 Fields are different (2)
Screenshot_2019-10-03 Fields are different (3)
Screenshot_2019-10-03 Fields are different (4)
Screenshot_2019-10-03 Fields are different (5)

### CODE REVIEW

**Comment by shell1** [comment]
- "active experiment name" in add-ons design should not be required (since that was a very confusing field and with new add-on capabilities we don't need that anymore.)  
- public name and description are required now (both pref flip and add-on)

**Comment by jaredkerim** [comment]
Oh right and the other caveat is on the design page the branches are still required to save because they have to be validated together.

**Comment by uhlissuh** [comment]
@jaredkerim oh that's an important piece of info for my current work..

**Comment by uhlissuh** [comment]
@jaredkerim it makes sense, but I don't think I had considered that fully.

**Comment by jaredkerim** [comment]
It occurs to me I should leave this for 2.42 because it introduces a lot of changes and I'd rather let the react stuff land and settle first.

**Pull request merged**
