### PR TITLE
fix #7386 feat(nimbus):Remove desktop redundant check from targeting

### LINKED ISSUE #7386: Remove extra check
The targeting property of NimbusExperiment checks if the locales is for the desktop or not. Once we add the UI to support languages for mobile Experiments, we can remove that extra check.

{{ if self.application == self.Application.DESKTOP:}}

Remove the special case for mobile locales after we add the languages UI.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2474)

### PR DESCRIPTION
**Pull request by yashika-khurana**
Because

* We transformed the Locales-> Languages for the Mobile experiments, the targeting property of NimbusExperiment checks if the locales are for the desktop or not. We have added  UI to support languages for mobile Experiments, we can remove that extra check.

`{{ if self.application == self.Application.DESKTOP:}}`

This commit

* Remove the check and test case associated with it

fix #7386 

Note: Blocked until we release this PR: https://github.com/mozilla/experimenter/pull/7405

### CODE REVIEW

**Review by jaredlockhart — DISMISSED** [review]
Oh you know what you'll need to do is change the mobile integration tests from `locales` to `languages` here:

https://github.com/mozilla/experimenter/blob/main/app/tests/integration/nimbus/conftest.py#L220

**Comment by jaredlockhart** [comment]
Also hooray for the mobile integration tests working correctly 🎉 🎉 🎉 🎉 🎉

**Comment by yashika-khurana** [comment]
> @jaredlockhart @eliserichards @jrbenny35 SDK doesn't support `Languages` at the moment, so I kept locale, once SDK supports that, I have filed a ticket to address this- #7448

PS: Ignore my previous comment

**Comment by jrbenny35** [comment]
Is this still blocked?

**Comment by yashika-khurana** [comment]
> Is this still blocked?

@jrbenny35 sorry, I just removed the label, its ready for review

**Review by eliserichards — APPROVED** [review]
This is awesome! Yay for deleting those TODOs 🎉

**Review by jrbenny35 — APPROVED** [review]

**Pull request merged**
