### PR TITLE
fixes #8254 Filling in a search query on Nimbus landing page before experiments load does not apply filter

### LINKED ISSUE #8254: Filling in a search query on Nimbus landing page before experiments load does not apply filter
If you start typing a search query, or possibly any other filter, before the experiments have finished loading, after they load they will not be filtered, so then you have to clear your filters and reapply them.  Maybe there's some way to apply the filters on the first load?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3131)

### PR DESCRIPTION
**Pull request by cherish2003**
### Because
 Filling in a search query of previous input on nimbus landing page before experiments load
### This commit
- Added `useeffect` hook to remove the `search` parameters after reload which is causing the bug
- Which results in the removal of `searchparameters` after the reload which is the solution to the issue 
### Screenshots
This issue is observable by reproduing it

### CODE REVIEW

**Comment by cherish2003** [comment]
@jaredlockhart @eliserichards @yashikakhurana Kindly check the code let me know any further changes are required

**Review by yashikakhurana — CHANGES_REQUESTED** [review]
thank you @cherish2003 for working on this, but unfortunately I tried that locally by creating 1500 experiments locally and this doesn't resolve the issue, and also you are working only for search term, but this issue is applicable for all the filters as well, so I would suggest to look more in detail for this

**Comment by cherish2003** [comment]
> thank you @cherish2003 for working on this, but unfortunately I tried that locally by creating 1500 experiments locally and this doesn't resolve the issue, and also you are working only for search term, but this issue is applicable for all the filters as well, so I would suggest to look more in detail for this

Okay mam I will work on the changes and let you know thank you for your response

**Comment by cherish2003** [comment]
@yashikakhurana Hi mam this issue is not reproducible and it work fine on my machine can you kindly check once

**Comment by cherish2003** [comment]
> @cherish2003 thank you for getting back, I mean to say this issue is applicable for all the filters whether it will be search, or selecting drop down and choosing channel, application etc, your PR only fixes for the search not for the other filters, please let me know if you have further questions, thanks

No mam i mean the filling in search query is not appearing i think it has been solved by some other PR's and also the` make check` is also while running it after downloading from repo @yashikakhurana can you kindly answers this quires 

The screen shot of the make check issue 

Screenshot from 2023-03-24 02-52-43

I have download the repository freshly and ran make check this issue is occurring i tried to resolve but i am unable to do it  and remaining seems to work fine

**Comment by yashikakhurana** [comment]
@cherish2003 my apologies I forgot to inform you-that we have reverted some code related to search- https://github.com/mozilla/experimenter/pull/8567 and https://github.com/mozilla/experimenter/pull/8568 so you might need to update your branch and see what you can do from there, so would suggest starting as fresh and create new PR with new approach

**Comment by cherish2003** [comment]
> @cherish2003 my apologies I forgot to inform you-that we have reverted some code related to search- #8567 and #8568 so you might need to update your branch and see what you can do from there, so would suggest starting as fresh and create new PR with new approach

Okay mam i will close this PR and make a new PR with new changes

**Pull request closed without merging**
