### PR TITLE
Add 'Max Firefox Version' , ref #880

### PR DESCRIPTION
**Pull request by leplatrem**
Ref #880 

- [x] Rename firefox version to firefox min version
- [ ] Add firefox max version
- [ ] Update templates and views
- [ ] Unit tests

### CODE REVIEW

**Comment by jaredkerim** [comment]
@leplatrem This is great so far!  Are you blocked or is there any way I can help?

**Comment by leplatrem** [comment]
> @leplatrem This is great so far! Are you blocked or is there any way I can help?

Thanks! I was doing other stuff this week and haven't touched it in the last days. Feel free to take over if you're in a hurry!

**Comment by jaredkerim** [comment]
@leplatrem No rush :)

**Comment by leplatrem** [comment]
Can somebody take over this one please?

I am very likely to be busy with other things in the next weeks...

**Comment by jaredkerim** [comment]
I think this has been abandoned so I will close it for now.

**Pull request closed without merging**
