### PR TITLE
Revert "chore(nimbus): decrease integration test celery timing (#5887)"

### LINKED ISSUE #5952: Intermittent test failure: Nimbus Remote Settings
The nimbus remote settings integration tests recently failed on circle:

https://app.circleci.com/pipelines/github/mozilla/experimenter/10295/workflows/bfb15bd8-8632-4083-b086-40e97eb9e46a/jobs/30301

```
nimbus/test_e2e_create_experiment.py::test_create_new_experiment PASSED  [ 25%]
nimbus/test_e2e_create_experiment.py::test_create_new_experiment_remote_settings FAILED [ 50%]
nimbus/test_e2e_create_experiment.py::test_create_new_experiment_remote_settings_reject FAILED [ 75%]
nimbus/test_e2e_create_experiment.py::test_create_new_experiment_remote_settings_timeout FAILED [100%]

=================================== FAILURES ===================================
__________________ test_create_new_experiment_remote_settings __________________

selenium = <selenium.webdriver.firefox.webdriver.WebDriver (session="f2ae3c97-c82c-4435-8ceb-d009f547e43d")>
base_url = 'https://nginx/nimbus'

    def test_create_new_experiment_remote_settings(selenium, base_url):
        experiment_name = f"name here remote {random.randint(0, 1000)}"
    
        selenium.get(base_url)
        home = HomePage(selenium, base_url).wait_for_page_to_load()
        current_experiments = None
        try:
            current_experiments = len(home.tables[0].experiments)
        except TimeoutException:
            current_experiments = 0
        experiment = home.create_new_button()
        experiment.public_name = experiment_name
        experiment.hypothesis = "smart stuff here"
        experiment.application = "DESKTOP"
    
        # Fill Overview Page
        overview = experiment.save_and_continue()
        overview.public_description = "description stuff"
        overview.select_risk_brand_false()
        overview.select_risk_revenue_false()
        overview.select_risk_partner_false()
    
        # Fill Branches page
        branches = overview.save_and_continue()
        branches.remove_branch()
        branches.reference_branch_name = "name 1"
        branches.reference_branch_description = "a nice experiment"
        branches.feature_config = "No Feature Firefox Desktop"
    
        # Fill Metrics page
        metrics = branches.save_and_continue()
    
        # Fill Audience page
        audience = metrics.save_and_continue()
        audience.channel = "Nightly"
        audience.min_version = 80
        audience.targeting = "US_ONLY"
        audience.percentage = 50.0
        audience.expected_clients = 50
        audience.save_btn()
        review = audience.save_and_continue()
    
        # Review and approve
        selenium.find_element_by_css_selector("#PageSummary")
        review.launch_without_preview.click()
        review.request_review.click_launch_checkboxes()
        review.request_review.request_launch_button.click()
        review.approve()
        selenium.get("http://kinto:8888/v1/admin")
        kinto_login = Login(selenium, base_url).wait_for_page_to_load()
        kinto_login.kinto_auth.click()
>       kinto_dashbard = kinto_login.login()

nimbus/test_e2e_create_experiment.py:105: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
nimbus/remote_settings/pages/login.py:34: in login
    return Dashboard(self.selenium, self.base_url).wait_for_page_to_load()
nimbus/remote_settings/pages/dashboard.py:13: in wait_for_page_to_load
    self.wait.until(EC.presence_of_element_located(self._bucket_menu_locator))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.support.wait.WebDriverWait (session="f2ae3c97-c82c-4435-8ceb-d009f547e43d")>
method = <selenium.webdriver.support.expected_conditions.presence_of_element_located object at 0x7f7d1f134580>
message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
        return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

.tox/integration-test-nimbus/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException
------------------------------- pytest-selenium --------------------------------
Driver log: /tmp/pytest-of-seluser/pytest-0/test_create_new_experiment_rem0/driver.log
URL: http://kinto:8888/v1/admin/#/
WARNING: Failed to gather log types: Message: HTTP method not allowed
______________ test_create_new_experiment_remote_settings_reject _______________

selenium = <selenium.webdriver.firefox.webdriver.WebDriver (session="96a3b8dd-0f1e-4162-a5a4-a5c07758f1a8")>
base_url = 'https://nginx/nimbus'

    def test_create_new_experiment_remote_settings_reject(selenium, base_url):
        experiment_name = f"name here remote {random.randint(0, 1000)}"
    
        selenium.get(base_url)
        home = HomePage(selenium, base_url).wait_for_page_to_load()
        home.tabs[-1].click()  # Click drafts
        experiment = home.create_new_button()
        experiment.public_name = experiment_name
        experiment.hypothesis = "smart stuff here"
        experiment.application = "DESKTOP"
    
        # Fill Overview Page
        overview = experiment.save_and_continue()
        overview.public_description = "description stuff"
        overview.select_risk_brand_false()
        overview.select_risk_revenue_false()
        overview.select_risk_partner_false()
    
        # Fill Branches page
        branches = overview.save_and_continue()
        branches.remove_branch()
        branches.reference_branch_name = "name 1"
        branches.reference_branch_description = "a nice experiment"
        branches.feature_config = "No Feature Firefox Desktop"
    
        # Fill Metrics page
        metrics = branches.save_and_continue()
    
        # Fill Audience page
        audience = metrics.save_and_continue()
        audience.channel = "Nightly"
        audience.min_version = 80
        audience.targeting = "US_ONLY"
        audience.percentage = 50.0
        audience.expected_clients = 50
        audience.save_btn()
        review = audience.save_and_continue()
    
        # Review and approve
        selenium.find_element_by_css_selector("#PageSummary")
        review.launch_without_preview.click()
        review.request_review.click_launch_checkboxes()
        review.request_review.request_launch_button.click()
        review.approve()
        selenium.get("http://kinto:8888/v1/admin")
        kinto_login = Login(selenium, base_url).wait_for_page_to_load()
        kinto_login.kinto_auth.click()
>       kinto_dashbard = kinto_login.login()

nimbus/test_e2e_create_experiment.py:184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
nimbus/remote_settings/pages/login.py:34: in login
    return Dashboard(self.selenium, self.base_url).wait_for_page_to_load()
nimbus/remote_settings/pages/dashboard.py:13: in wait_for_page_to_load
    self.wait.until(EC.presence_of_element_located(self._bucket_menu_locator))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.support.wait.WebDriverWait (session="96a3b8dd-0f1e-4162-a5a4-a5c07758f1a8")>
method = <selenium.webdriver.support.expected_conditions.presence_of_element_located object at 0x7f7d1f206f40>
message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
        return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

.tox/integration-test-nimbus/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException
------------------------------- pytest-selenium --------------------------------
Driver log: /tmp/pytest-of-seluser/pytest-0/test_create_new_experiment_rem1/driver.log
URL: http://kinto:8888/v1/admin/#/
WARNING: Failed to gather log types: Message: HTTP method not allowed
______________ test_create_new_experiment_remote_settings_timeout ______________

selenium = <selenium.webdriver.firefox.webdriver.WebDriver (session="b24f6e1c-2fed-4705-bf04-bfefcc95293e")>
base_url = 'https://nginx/nimbus'

    def test_create_new_experiment_remote_settings_timeout(selenium, base_url):
        experiment_name = f"name here remote {random.randint(0, 1000)}"
    
        selenium.get(base_url)
        home = HomePage(selenium, base_url).wait_for_page_to_load()
        experiment = home.create_new_button()
        experiment.public_name = experiment_name
        experiment.hypothesis = "smart stuff here"
        experiment.application = "DESKTOP"
    
        # Fill Overview Page
        overview = experiment.save_and_continue()
        overview.public_description = "description stuff"
        overview.select_risk_brand_false()
        overview.select_risk_revenue_false()
        overview.select_risk_partner_false()
    
        # Fill Branches page
        branches = overview.save_and_continue()
        branches.remove_branch()
        branches.reference_branch_name = "name 1"
        branches.reference_branch_description = "a nice experiment"
        branches.feature_config = "No Feature Firefox Desktop"
    
        # Fill Metrics page
        metrics = branches.save_and_continue()
    
        # Fill Audience page
        audience = metrics.save_and_continue()
        audience.channel = "Nightly"
        audience.min_version = 80
        audience.targeting = "US_ONLY"
        audience.percentage = 50.0
        audience.expected_clients = 50
        audience.save_btn()
        review = audience.save_and_continue()
    
        # Review and approve
        selenium.find_element_by_css_selector("#PageSummary")
        review.launch_without_preview.click()
        review.request_review.click_launch_checkboxes()
        review.request_review.request_launch_button.click()
        review.approve()
        for attempt in range(45):
            try:
                review = SummaryPage(selenium, base_url).wait_for_page_to_load()
                review.timeout_text
            except NoSuchElementException:
                time.sleep(2)
                selenium.refresh()
            else:
                assert review.timeout_text, "Timeout text not shown."
                break
        else:
>           raise AssertionError("Timeout text was never shown.")
E           AssertionError: Timeout text was never shown.

nimbus/test_e2e_create_experiment.py:286: AssertionError
------------------------------- pytest-selenium --------------------------------
Driver log: /tmp/pytest-of-seluser/pytest-0/test_create_new_experiment_rem2/driver.log
URL: https://nginx/nimbus/name-here-remote-809/
WARNING: Failed to gather log types: Message: HTTP method not allowed
=========================== short test summary info ============================
FAILED nimbus/test_e2e_create_experiment.py::test_create_new_experiment_remote_settings
FAILED nimbus/test_e2e_create_experiment.py::test_create_new_experiment_remote_settings_reject
FAILED nimbus/test_e2e_create_experiment.py::test_create_new_experiment_remote_settings_timeout
=================== 3 failed, 1 passed in 282.74s (0:04:42) ====================
ERROR: InvocationError for command /code/app/tests/integration/.tox/integration-test-nimbus/bin/pytest --verify-base-url --base-url https://nginx/nimbus --self-contained-html --driver Firefox nimbus/ -vvv (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   integration-test-nimbus: commands failed
ERROR: 1
make: *** [Makefile:164: integration_test_nimbus] Error 1
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1489)

### PR DESCRIPTION
**Pull request by jrbenny35**
Closes #5952

### CODE REVIEW

**Review by jaredlockhart — APPROVED** [review]
👍 👍 👍 👍 That'll teach me to mess with your settings 🤣

**Comment by pdehaan** [comment]
Sure sure, but can somebody tell me _why_ reverting these values (back to @jrbenny35's original values) fixes the issue?

```diff
-CELERY_SCHEDULE_INTERVAL=5
+CELERY_SCHEDULE_INTERVAL=30
-KINTO_REVIEW_TIMEOUT=10
+KINTO_REVIEW_TIMEOUT=60
```

Is the problem that we have `for attempt in range(45):` and we should increase the max number of attempts (check more, but faster) or just revert the previous PR to the original settings?
Or do we find a number in the middle and see where the breaking point is? (so celery polls every 15s and kinto every 30s)?

Sorry, just lots of numbers floating around (not even including `time.sleep(2)`) and I'm curious exactly which part was causing the test failure.

Curiously, I see this PR ran the "ci/circleci: integration_numbus" check ran in **8m 14s**.
Looking at a different, random PR, it looks like the tests ran in [**5m 48s**](https://app.circleci.com/pipelines/github/mozilla/experimenter/10322/workflows/ed5b8cbe-217d-4d9f-b612-088de0772232/jobs/30430). Although 2 random data points don't really prove anything, so maybe I'll randomly sample a few other PRs before and after the previous PR was merged to try and see if goosing the values really does speed up tests by ~2 mins.

**Comment by jaredlockhart** [comment]
@pdehaan yeah good questions.  You're right that it does change the time to run which is why I changed it in the first place.  The circle task times are misleading, the real time to look at is the actual test run time.

With 30/60:
4 passed in 171.10s (0:02:51)

With 5/10:
4 passed in 81.43s (0:01:21)


It's a pretty significant difference.  When we have a lot more of these tests we'll definitely have to bring that down.  I think the goal here is to turn them back up and see if that addresses the intermittency.  If it does we know it's a timing issue.  If it doesn't then it's something else.  I think it's worth while trying and seeing.  These kinds of intermittent integration test failures are difficult to debug so if we can offload some of the work onto circle for us then that's a good way to save some time.

**Comment by pdehaan** [comment]
> Although 2 random data points don't really prove anything,

☝️ Righto, sport!
After randomly sampling a few other PRs, I came to the conclusion that trying to infer anything from test run times is ... challenging and mostly pointless.
Well, that and the actual test execution times are pretty quick/consistent compared to the overhead of the rest of CI setup.

### w/ Jared's tweaks

| CI | pytest | pytest % of CI time
|---:|:------:|----:|
| [3m 17s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10292/workflows/44115ffa-a3fb-4f9d-9e1a-0d246582e85d/jobs/30289) | 4 passed in 74.59s (0:01:14) | 38.46%
| [4m 13s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10312/workflows/7f255a71-763b-4e70-b125-aa6d0a4cab70/jobs/30379) | 4 passed in 71.96s (0:01:11) | 28.57%
| [5m 46s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10249/workflows/0c02bfb7-805b-46a2-ac6d-63c322cb095c/jobs/30117) | 4 passed in 76.55s (0:01:16) | 21.74%
| [7m 1s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10321/workflows/76c897a1-6f87-4d85-8e3a-c487e5dabe4b/jobs/30425)| 4 passed in 76.50s (0:01:16) | 17.86%
| [9m 7s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10177/workflows/22c4655b-a287-4c1e-ab47-19a3757eb403/jobs/29802) | 4 passed in 74.74s (0:01:14) | 13.59%

### Pre Jared's tweaks

| CI | pytest | pytest % of CI time
|---:|:------:|----:|
| [7m 44s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10083/workflows/22cd466a-3e57-4571-884e-e73dd27131b9/jobs/29435) | 4 passed in 173.98s (0:02:53) | 38.71%
| [9m 3s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10076/workflows/83459492-94f2-445c-893b-e85f408adc37/jobs/29400) | 4 passed in 173.53s (0:02:53) | 32.22%
| [8m 6s](https://app.circleci.com/pipelines/github/mozilla/experimenter/9986/workflows/270fd4cf-6812-419e-9c55-628b50580a7a/jobs/29009) | 2 passed in 50.50s | 11.11%
| [8m 52s](https://app.circleci.com/pipelines/github/mozilla/experimenter/10017/workflows/36c5b92b-3ac0-4f6a-a182-12cc84b135dd/jobs/29148) | 2 passed in 52.07s | 10.11%

---

So looking at the general CircleCI run (for a [random run](https://app.circleci.com/pipelines/github/mozilla/experimenter/10177/workflows/22c4655b-a287-4c1e-ab47-19a3757eb403/jobs/29802) I happen to have open; and has Jared's tweaks applied), we currently have 6 steps for the nimbus integration tests:

| NAME | TIME | TOTAL: 9m 7s
|:-----|-----:|-----:|
| Spin up environment | 1m 25s | 15.54%
| Preparing environment variables | 0s | 0%
| Docker info | 0s | 0%
| Docker compose info | 1s| 0%
| Checkout code | 2s | 0%
| Run integration tests | 7m 33s | 82.82%
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &mdash; pytests | 1m 14s | 13.57%<sup>1</sup>

<sup>1</sup> The pytest times are a %% of the total build time and are also included in the overall "Run integration tests" timings, which is why this is well over 100% if you try and add up that column.

I'm guessing "Spin up env" can't be optimized much.
The "Run integration tests" takes up the other ~83% of the total build time. We know that the tests themselves run in 1m 14s, or ~16.67% of the total **step** time, and the Dockering seems to consume the other ~6m.

**Comment by pdehaan** [comment]
Anyways, I think I lost the point I was trying to originally make... I'm fine w/ reverting the changes, but we might want to file a new ticket for one/both of:
1. Re-tweak the numbers and see if there is a middle ground between 30/60 and 5/10 which will give us some speed gains.
2. See if there is any Docker optimizations we can make for the tests+caching which will probably/hopefully/maybe have a better performance impact than adjusting the timeouts.

**Comment by jaredlockhart** [comment]
@pdehaan Thanks for digging in!  Yeah I think I'd like to see if reverting it clears up the intermittency so know that's what's causing it and not something else, then we can try dialing them down.  Also 2 has been my focus this week.

**Review by pdehaan — APPROVED** [review]

**Pull request merged**
