### PR TITLE
hotfix(nimbus): Add col

### PR DESCRIPTION
**Pull request by yashika-khurana**
Because

    The row should have a col component inside it

This commit

    Adds a Col inside Row component on the landing page

image

### CODE REVIEW

**Review by jaredlockhart — DISMISSED** [review]
Yes 🙏 but also for the filters too 🙏 🙏 🙏 🙏

**Comment by jaredlockhart** [comment]
Also it occurred to me the labels on the buttons might look better left aligned, I was just looking at this example in my messenger app:

Screen Shot 2022-10-26 at 5 52 45 PM

**Review by eliserichards — APPROVED** [review]
r+ once you add the col for the filters 😄

**Comment by yashika-khurana** [comment]
@jaredlockhart Added Col filtering, this how it looks with left align now
image

**Comment by jaredlockhart** [comment]
@yashika-khurana thank you for the updates, I don't know if the left aligned buttons are better or worse than the centre aligned ones, I was just curious to see if they looked better, @eliserichards @yashika-khurana what do you think?  I'd say pick either.

Also yes but the filters are still misaligned with the buttons, the point I'm trying to make is everything in the column aligning the same way, you see what I mean?  So there's probably some additional padding inside that component you can remove now.

**Comment by yashika-khurana** [comment]
@jaredlockhart I liked the centre aligned one, but I am open for make left aligned as well, upto you @eliserichards 😶‍🌫️ , and yes let me fix col thing

**Comment by eliserichards** [comment]
Center aligned! 🙋‍♀️

**Comment by yashika-khurana** [comment]
@jaredlockhart Navbar was the culprit 😆 , here you go 🚀  
image

**Comment by eliserichards** [comment]
👏 🚀

**Pull request merged**
