### PR TITLE
fixes #7919 test(Nimbus): Update integration test file names

### LINKED ISSUE #7919: Update Integration Test file names
With the new changes to how we select and run integration tests, we should update the names/regorganize the tests to match how they are selected to run.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2920)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/EXP-2920

### PR DESCRIPTION
**Pull request by jrbenny35**
Because:
* We have just reoganized our CI jobs to be more descriptive but our test suites are still a bit out of order

This Commit:
* Updates the test suite names to match the tests within them a bit better.
* Moves some tests around

### CODE REVIEW

**Review by jaredlockhart — CHANGES_REQUESTED** [review]
Awesome thank you, couple ideas:

`test_client_integrations.py` this is only testing desktop enrollment, maybe mention desktop and enrollment in the name?

`test_mobile_integrations` this is testing mobile targeting, maybe mention targeting in the name?

`test_targeting` this is only testing desktop, maybe mention that?

**Comment by jrbenny35** [comment]
> Awesome thank you, couple ideas:
> 
> `test_client_integrations.py` this is only testing desktop enrollment, maybe mention desktop and enrollment in the name?
> 
> `test_mobile_integrations` this is testing mobile targeting, maybe mention targeting in the name?
> 
> `test_targeting` this is only testing desktop, maybe mention that?

So you'd rather more ```.py``` files with more specific names versus trying to encompass a lot of tests into a few files?

**Comment by jaredlockhart** [comment]
> > Awesome thank you, couple ideas:
> > `test_client_integrations.py` this is only testing desktop enrollment, maybe mention desktop and enrollment in the name?
> > `test_mobile_integrations` this is testing mobile targeting, maybe mention targeting in the name?
> > `test_targeting` this is only testing desktop, maybe mention that?
> 
> So you'd rather more `.py` files with more specific names versus trying to encompass a lot of tests into a few files?

You could do it either way, I'm just suggesting if a file is only testing desktop it would be helpful to have desktop in the name, if it's only testing enrollment it would be helpful to have enrollment in the name, instead of something more generic like 'integrations'.

**Review by jaredlockhart — APPROVED** [review]
Awesome thank you! 🎉

**Pull request merged**
