### PR TITLE
Pin package versions and hashes Fixes #601

### LINKED ISSUE #601: Pin package versions and hashes
We should probably start pinning all our package versions and hashes so we don't wind up in situations where docker builds are cached and inconsistent.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #601

Notable changes are that I also upgraded `psycopg2` and `Django` and added `requests[security]` so it installs all the good security packages. 

What really bothers me is the number of development packages that get installed but are never needed beyond CI. What we *really* should do is break up `requirements/default.txt` into a list of packages that are actually needed and then have a separate `requirements/dev.txt` that is only installed by developers (locally) and somewhere in `docker-compose.test.yml`. For example, we don't need `coverage` or `ipdb` in the docker image we ship into production. One battle at a time I guess.

### CODE REVIEW

**Comment by jaredkerim** [comment]
This is great @peterbe thanks!  Please ammend the commit to include 'fixes #601' at the end of the commit message and repush and I'll merge it.  I realize I should have written a contributing.md before people joined, but I'll do that now.

**Comment by peterbe** [comment]
At the end? This is how we use it on Normandy and a bunch of other product-delivery projects. But sure, I'll try to change my git automation tools.

**Comment by peterbe** [comment]
By the way, the commit message already has the "Fixes #XXX" at the bottom of the message. Whether or not the GitHub PR description becomes the commit message depends on how we land PRs in this project. Do we use bors or do we use "Squash and merge" or do we use "Rebase and merge"?

**Comment by peterbe** [comment]
See; output from `git log`
```
commit 7f2fe555743daab0b6644b184313d16a10348986 (HEAD -> 601-pin-package-versions-and-hashes)
Author: Peter Bengtsson <mail@peterbe.com>
Date:   Tue Feb 12 16:36:33 2019 -0500

    Pin package versions and hashes

    Fixes #601
```

**Pull request merged**
