### PR TITLE
Clears the filters when we create new experiment with filters applied in home page 

### LINKED ISSUE #8254: Filling in a search query on Nimbus landing page before experiments load does not apply filter
If you start typing a search query, or possibly any other filter, before the experiments have finished loading, after they load they will not be filtered, so then you have to clear your filters and reapply them.  Maybe there's some way to apply the filters on the first load?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3131)

### PR DESCRIPTION
**Pull request by cherish2003**
### Because
When we apply filters in home page and go to create new `Experiment` then come to home page then the filters are automatically applied .This has to be removed to rectify this issue

### This commit
- Removed the attributes of the filters from the storage when navigation happens from one page to another page 
- closes #8254 
### Screenshots
Screenshot from 2023-03-30 02-14-32

### CODE REVIEW

**Comment by cherish2003** [comment]
@yashikakhurana kindly review the code and let me know any changes are required

**Comment by yashikakhurana** [comment]
@cherish2003 I think you misunderstood, when we create a new experiment and the filters are already applied, we want to preserve those and that is working fine, the issue is not with that. The issue is when we launch the localhost, you will see it takes time to load the experiments on the browser, and in meanwhile if you apply filters before  the completion of loading of experiments, and the loaded gets completed, filters have no effect, you have to manually remove it and then apply filters again actually to see the difference, let me know if you have any questions, feel free to close this PR and create a new one once you finish working on :)

**Comment by yashikakhurana** [comment]
@cherish2003 couple of things can be done, may be disable filters completely when loading or let the users apply filters and when we see loading is completed we make sure those filters are applied, I will let you look into this more

**Comment by cherish2003** [comment]
> @cherish2003 couple of things can be done, may be disable filters completely when loading or let the users apply filters and when we see loading is completed we make sure those filters are applied, I will let you look into this more

Okay mam i will work on it and inform you about updates

**Comment by yashikakhurana** [comment]
@cherish2003 I am closing this PR for now :)

**Pull request closed without merging**
