### PR TITLE
Add multi-pref e2e integration test, issue #2224

### LINKED ISSUE #2224: End to End Test: Pref Experiment (Multipref)

### PR DESCRIPTION
**Pull request by jrbenny35**
Closes #2224

### CODE REVIEW

**Comment by jaredlockhart** [comment]
Oh @tiftran did this for you, you probably need to update to latest master:

https://github.com/mozilla/experimenter/pull/2565

**Comment by jrbenny35** [comment]
> Oh @tiftran did this for you, you probably need to update to latest master:
> 
> #2565

@tiftran you rock

**Comment by jrbenny35** [comment]
How would you like to add this to circleci? Right now it just runs with the tests we currently have. @jaredlockhart

**Comment by jaredlockhart** [comment]
@jrbenny35 Yeah exactly just run it with the current integration tests.  So we'll keep adding these e2e tests, the integration test suite will get bigger and when we feel like we've got good enough coverage we can take out the individual field tests and it'll shrink back down.

**Pull request merged**
