### PR TITLE
fixes #8451 fix(nimbus): In the audience page add a check so that val…

### LINKED ISSUE #8451: Don't let numbers start with zero on Audience page
Steps to reproduce:
1. Create a new experiment Draft
2. On the audience page, fill in the "Expected number of clients" field with a number starting with zero (e.g. "050")

Expected:
The UI tells you that it isn't a valid number

Actual: 
The number can be saved and is valid. When you navigate to another page and come back, the number has been correctly formatted (if you entered "050" it now shows "50"). 

image

We should either:

1. Show a warning when a number begins with 0
or 
2. When the user saves, it should format the number

### PR DESCRIPTION
**Pull request by Prithvi-Chanchal**
…ue of number of clients can not start with zero and also add a test case to check this issue

Because

- In the audience page total number of clients form can have value starting with zero

This commit

- add the check to so that if user input any number starting with zero it will through an error and will only accepts number that does not start with zero
- add a test case to check this in test file also

### CODE REVIEW

**Comment by Prithvi-Chanchal** [comment]
@yashika-khurana I could not grasp what the error is could you please help me in this one, I would really appreciate it.

**Comment by yashikakhurana** [comment]
@Prithvi-Chanchal some of the integration tests are failing

**Comment by Prithvi-Chanchal** [comment]
@yashikakhurana thank you for your response ma'am, I checked the ci and checked the files in the path you specified, in the integration test "test_experimenter_ui.py" we are getting all the errors. All the functions there fails when they are creating new experiment and this happening because of save_and_continue() function in create_experiement() function because it fails to return audience.save_and_continue() in time. So it gives timeout error. Now I am looking why this happening, if you have anything that could help please do guide me. thank you ma'am

**Comment by yashikakhurana** [comment]
@Prithvi-Chanchal I haven't looked at the integration test yet for your use case, couple of thoughts, you can run integration tests locally, can find instructions on readme  how to run them, and can see what is happening while running those, other things since you have changed the message may be integration test is expecting different value, or may check what input is getting provided in integration tests, I will let you dig this into more :)

**Comment by Prithvi-Chanchal** [comment]
@yashikakhurana ma'am I ran the integration tests locally but it took so much time to get ran those now I have what the errors are  and I am still looking how I can fix this, also I have an exam coming up this Friday so I will busy with that also So I will take some more time to fix this issue, sorry for inconvenience

**Comment by yashikakhurana** [comment]
@Prithvi-Chanchal no rush thank you for letting me know, I am closing this PR for now, feel free to create new one, once you finish working on this and good luck for your exams :)

**Comment by Prithvi-Chanchal** [comment]
@yashikakhurana thank you ma'am, ma'am could you please check your mail I have send you and give me some feedback about it.

**Pull request closed without merging**
