### PR TITLE
feat(nimbus): Update UI for localized experiments

### LINKED ISSUE #8712: Experiment localization support in Experimenter console
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3166)

### PR DESCRIPTION
**Pull request by brennie**
Because

- we want to support localized experiments in Nimbus

this commit

- updates the UI to support localized experiments.

Fixes #8712

Co-authored-by: Jason Prickett <jprickett@mozilla.com>

### CODE REVIEW

**Comment by yashikakhurana** [comment]
Unblocking this PR

**Review by jaredlockhart — COMMENTED** [review]
Tested locally, everything worked perfectly, fantastic work 🎉 🎉 🎉 🎉 

Couple questions

1) Why are all those version check tests removed?

2) I thought the localizations form was going to be on the branch page since that's where the localized content is also entered.  What do you think?  I'm okay with either just curious if you felt strongly about putting it on the overview page?

**Comment by brennie** [comment]
> Tested locally, everything worked perfectly, fantastic work 🎉 🎉 🎉 🎉 
> 
> Couple questions
> 
> 1) Why are all those version check tests removed?

That is from a bad rebase.

> 2) I thought the localizations form was going to be on the branch page since that's where the localized content is also entered.  What do you think?  I'm okay with either just curious if you felt strongly about putting it on the overview page?

Jason put it on the overview page, but I can move it to the branch page.

**Comment by jaredlockhart** [comment]
@brennie Awesome thank you let's move it to the branch page I think that'll make more sense 🙏

**Review by jaredlockhart — APPROVED** [review]
Looks great let's goooooooo 🏁 🏁 🏁 💨

**Pull request merged**
