### PR TITLE
fix #4399 chore(nimbus): remove admin validation

### LINKED ISSUE #4399: Remove Nimbus admin validation
We added a bunch of rich validation to the NimbusExperiment admin when we were temporarily using it to launch experiments.  Now that the full UI is ready for use, we don't need this logic anymore and we should rip it out.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-817)
┆Issue Number: EXP-817

### PR DESCRIPTION
**Pull request by jaredlockhart**
Because

- We are no longer using the admin to launch nimbus experiments

This commit

- Removes the additional rich validation we added to support that workflow

### CODE REVIEW

**Comment by lmorchard** [comment]
Do we not want JSON schema validation in admin when possible? Seems like that would be a good handrail to not break the JSON if/when we *do* find a need to tinker with it from admin

**Comment by jaredlockhart** [comment]
@lmorchard Yeah we could keep it, generally I treat the admin as just the 'you can dump anything in here you need to' panel for emergencies so typically you want it to be as basic as possible.  But on the other hand, I can't think of a case where we'd WANT to dump json that doesn't match the schema of the feature, so maybe we should just keep it and if it becomes a problem we can either update it or remove it in the future?  What do you think?

**Review by lmorchard — APPROVED** [review]
I can really go either way... Kind of like to have some data integrity checks all the way to admin panel to keep guns pointed away from feet. But could help in cases where otherwise we'd have to drop down to something like direct DB queries. :shrug:

**Comment by jaredlockhart** [comment]
@lmorchard yeah exactly, if it comes up that we ended up needing it we can revert easily.

**Pull request merged**
