### PR TITLE
Fixes #8022 test(nimbus): Add lifecycles and lifecycle states for dirty

### LINKED ISSUE #8022: Update test factories to include all lifecycles
We're currently missing a few lifecycles and lifecycle states in our test factory. Let's update this so it makes things easier for adding the Dirty publish status for rollouts

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2973)

### PR DESCRIPTION
**Pull request by eliserichards**
Because...

* We want our test factories to cover the full extent of our status and publish status lifecycles

This commit...

* Adds the following `LifecycleStates` for the `DIRTY` publish status:
   * LIVE_DIRTY
   * LIVE_REVIEW
   * LIVE_APPROVED
   * LIVE_APPROVED_UNPAUSED
   * LIVE_APPROVED_WAITING
   * LIVE_WAITING_UNPAUSED
   * LIVE_IDLE_REJECT

* Adds the following `Lifecycles` for `DIRTY` (these cover all scenarios in the [sequence diagrams](https://github.com/mozilla/experimenter/blob/main/app/experimenter/docs/README.md#update-approveapprove)):
   * LIVE_DIRTY
   * LIVE_REVIEW_REQUESTED
   * LIVE_REJECT
   * LIVE_APPROVE
   * LIVE_APPROVE_WAITING
   * LIVE_APPROVE_APPROVE
   * LIVE_APPROVE_REJECT
   * LIVE_APPROVE_TIMEOUT
   * LIVE_REJECT_MANUAL_ROLLBACK

* Adds a few missing `Lifecycles` (these are in our sequence diagrams but were not represented here):
   * LAUNCH_APPROVE_REJECT
   * LAUNCH_REJECT_MANUAL_ROLLBACK
   * ENDING_REJECT
   * ENDING_APPROVE_REJECT
   * ENDING_REJECT_MANUAL_ROLLBACK

For #8022

### CODE REVIEW

**Comment by eliserichards** [comment]
I'm curious about the two unused LifecycleStates (LIVE_IDLE_REJECT_ENDING, LIVE_IDLE_ENROLLING), if these are necessary, or if they're ok to remove 🤔

**Comment by yashika-khurana** [comment]
for `LIVE_IDLE_ENROLLING`, I think we should keep it as it states that enrolling is live  `LIVE_ENROLLING = LAUNCH_APPROVE_APPROVE + (LifecycleStates.LIVE_IDLE_ENROLLING,)`
similarly for the other as well 
`ENDING_APPROVE_REJECT = ENDING_APPROVE_WAITING + (
        LifecycleStates.LIVE_IDLE_REJECT_ENDING,
    )`
depicting behaviour that ending approved got rejected 👀

**Review by jaredlockhart — DISMISSED** [review]
> I'm curious about the two unused LifecycleStates (LIVE_IDLE_REJECT_ENDING, LIVE_IDLE_ENROLLING), if these are necessary, or if they're ok to remove 🤔

Oh oh, yeah, there's a bunch of places where we loop over all the lifecycles without referring to them explicitly:

https://github.com/mozilla/experimenter/blob/1bea0387a44a2cd032ac219dc161b49ebc2a33f2/app/experimenter/experiments/tests/api/v6/test_views.py#L17

so yeah I'd leave them all in.  Otherwise I think this all looks right.

**Review by yashika-khurana — APPROVED** [review]
All states make clear sense now, I was just looking at the ppt @jaredlockhart shared where they have mentioned states- 
image

 it would be good to have something which clearly gives the definition of each state like what they mean
Thank you @eliserichards ❤️

**Comment by eliserichards** [comment]
I like that idea! I will file a ticket for that to beef up our docs in `constants`. I think it will make things much more clear 🙌

**Pull request merged**
