### PR TITLE
fixes #8451 fix(nimbus): In the audience page add a check so that value of number of clients can not start with zero and also add a test case to check this issue

### LINKED ISSUE #8451: Don't let numbers start with zero on Audience page
Steps to reproduce:
1. Create a new experiment Draft
2. On the audience page, fill in the "Expected number of clients" field with a number starting with zero (e.g. "050")

Expected:
The UI tells you that it isn't a valid number

Actual: 
The number can be saved and is valid. When you navigate to another page and come back, the number has been correctly formatted (if you entered "050" it now shows "50"). 

image

We should either:

1. Show a warning when a number begins with 0
or 
2. When the user saves, it should format the number

### PR DESCRIPTION
**Pull request by Prithvi-Chanchal**
Because

- In the audience page total number of clients form can have value starting with zero

This commit

- add the check to so that if user input any number starting with zero it will through an error and will only accepts number that does not start with zero
- add a test case to check this in test file also

### CODE REVIEW

**Comment by Prithvi-Chanchal** [comment]
@emmaz12  could you please check I have made the PR

**Comment by yashikakhurana** [comment]
@Prithvi-Chanchal your test cases are failing, I will suggest working on that too

**Comment by yashikakhurana** [comment]
@Prithvi-Chanchal are you still working on fixing the test or should I close the PR?

**Comment by yashikakhurana** [comment]
@Prithvi-Chanchal I am not sure if you are working on this, closing for now, please feel free to open a new PR once you finish modifying test cases too, thank you

**Comment by Prithvi-Chanchal** [comment]
@yashikakhurana ma'am I am having end sem examination from monday so I am currently studying for that also but I am also working on it ma'am

**Pull request closed without merging**
