### PR TITLE
Disabling source maps 

### LINKED ISSUE #3055: 404 on CSS source map
Randomly spotted in devtools console while trying to submit a new Rapido experiment.

```
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css
Source Map URL: /static/assets/index.css.map
```

https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css defines the source map at the bottom:

```css
/*# sourceMappingURL=/static/assets/index.css.map */
```

This 404s https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css.map, which explains the source map parsing error.

I think the core problem is that the CSS has an invalid path to the source map:

- /static/assets/css/index.css
- /static/assets/index.css.map (I do believe this needs to be in the css/ directory along with the CSS file, not in the parent dir)

Note that going to https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css.map directly prompts you to download the index.css.map file, so we know the path is correct.

### PR DESCRIPTION
**Pull request by bhushan-borole**
Fixes #3055

### CODE REVIEW

**Comment by jaredlockhart** [comment]
@pdehaan Do you want to review this?

**Comment by jaredlockhart** [comment]
@pdehaan @bhushan-borole Thanks for taking this! 🎉

**Comment by jaredlockhart** [comment]
@pdehaan @bhushan-borole I just also wanted to mention that I confirmed this doesn't prevent proper JS debugging:

Screen Shot 2020-08-12 at 4 33 18 PM

So I think this just cleans up the deployment bundles.  Thnx again!

**Comment by bhushan-borole** [comment]
@pdehaan @jaredlockhart 
Thank you so much for merging!!

**Pull request merged**
