### PR TITLE
For #8607 docs(nimbus): Update documentation to include Windows info

### PR DESCRIPTION
**Pull request by KramStyles**
Because

- Windows users are finding it difficult to build the project successfully on their local machine. This PR provides a solution to Windows users experiencing build issues. 

This commit

- Add detailed steps for installing WSL, Docker, Make, and Git on Windows
- Provide instructions for setting up and integrating Ubuntu with Docker
- Include steps for building the project using the Ubuntu terminal in VS Code

### CODE REVIEW

**Review by jrbenny35 — CHANGES_REQUESTED** [review]
Thanks for the PR @KramStyles! This is looking good but I noticed there are a few steps that don't necessarily relate to windows. Also, it seems you duplicated a lot of the steps already mentioned in the setup steps. I think expanding on the steps is fine, but putting them all under windows (when they're technically in Linux) wouldn't make much sense. Could you shorten this PR to just include the specific windows steps needed? i.e.: installing WSL, and docker, and the initial wsl ubuntu setup.

**Comment by KramStyles** [comment]
> Thanks for the PR @KramStyles! This is looking good but I noticed there are a few steps that don't necessarily relate to windows. Also, it seems you duplicated a lot of the steps already mentioned in the setup steps. I think expanding on the steps is fine, but putting them all under windows (when they're technically in Linux) wouldn't make much sense. Could you shorten this PR to just include the specific windows steps needed? i.e.: installing WSL, and docker, and the initial wsl ubuntu setup.

@jrbenny35 Thank you for the feedback. I'd make the corrections now.

**Comment by KramStyles** [comment]
@jrbenny35 I've made the changes. The installation details for `Make` and `Git` were left because they relate to the `WSL ubuntu` setup as it's basically a new environment without `Make` installed. 

Do you want me to take it off too?

**Comment by KramStyles** [comment]
@yashika-khurana Hello, please I don't know why the test failed.

**Comment by yashikakhurana** [comment]
@KramStyles don't worry its not related to your changes :)

**Review by yashikakhurana — COMMENTED** [review]
I will let @jrbenny35 give a final pass, thank you @KramStyles

**Pull request merged**
